CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, applied_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS tenants (id TEXT PRIMARY KEY, slug TEXT NOT NULL UNIQUE, name TEXT NOT NULL, industry TEXT NOT NULL, settings_json TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS roles (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, key TEXT NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', is_admin INTEGER NOT NULL DEFAULT 0, can_create_incidents INTEGER NOT NULL DEFAULT 1, can_upload_knowledge INTEGER NOT NULL DEFAULT 0, UNIQUE (tenant_id, key));
CREATE TABLE IF NOT EXISTS permissions (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, role_key TEXT NOT NULL, department TEXT NOT NULL, max_classification TEXT NOT NULL, UNIQUE (tenant_id, role_key, department));
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, name TEXT NOT NULL, email TEXT NOT NULL, role_key TEXT NOT NULL, department TEXT NOT NULL, title TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, UNIQUE (tenant_id, email));
CREATE TABLE IF NOT EXISTS documents (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, title TEXT NOT NULL, filename TEXT NOT NULL, department TEXT NOT NULL, category TEXT NOT NULL, classification TEXT NOT NULL, source_type TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', allowed_roles_json TEXT NOT NULL DEFAULT '[]', allowed_users_json TEXT NOT NULL DEFAULT '[]', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS document_versions (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE CASCADE, version TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', effective_date TEXT NOT NULL, uploaded_at TEXT NOT NULL, uploaded_by TEXT NOT NULL, storage_path TEXT NOT NULL, checksum TEXT NOT NULL, char_count INTEGER NOT NULL DEFAULT 0, chunk_count INTEGER NOT NULL DEFAULT 0, ingest_status TEXT NOT NULL DEFAULT 'pending', ingest_error TEXT, UNIQUE (tenant_id, document_id, version));
CREATE TABLE IF NOT EXISTS document_chunks (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, document_id TEXT NOT NULL, version_id TEXT NOT NULL REFERENCES document_versions(id) ON DELETE CASCADE, seq INTEGER NOT NULL, section TEXT NOT NULL DEFAULT '', text TEXT NOT NULL, char_count INTEGER NOT NULL DEFAULT 0, keywords TEXT NOT NULL DEFAULT '', embedding BYTEA, embedding_model TEXT NOT NULL DEFAULT '', injection_flags TEXT NOT NULL DEFAULT '[]');
CREATE TABLE IF NOT EXISTS conversations (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, user_id TEXT NOT NULL, title TEXT NOT NULL, state_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, user_id TEXT NOT NULL, role TEXT NOT NULL, content TEXT NOT NULL, grounding TEXT, confidence TEXT, provider TEXT, latency_ms INTEGER, action_json TEXT, feedback TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS citations (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, message_id TEXT NOT NULL REFERENCES messages(id) ON DELETE CASCADE, document_id TEXT NOT NULL, version_id TEXT NOT NULL, chunk_id TEXT NOT NULL, document_title TEXT NOT NULL, department TEXT NOT NULL, version TEXT NOT NULL, section TEXT NOT NULL, score DOUBLE PRECISION NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS activity_logs (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, user_id TEXT, user_name TEXT, action TEXT NOT NULL, resource_type TEXT NOT NULL, resource_id TEXT, status TEXT NOT NULL, detail TEXT, request_id TEXT, latency_ms INTEGER, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS incidents (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, code TEXT NOT NULL, machine_id TEXT NOT NULL, description TEXT NOT NULL, severity TEXT NOT NULL, location TEXT NOT NULL, observed_at TEXT NOT NULL, reporter TEXT NOT NULL, reporter_user_id TEXT, conversation_id TEXT, status TEXT NOT NULL DEFAULT 'open', simulated INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, UNIQUE (tenant_id, code));
// hist: 2026-09-23T11:29:23+05:30
