-- NOVA Phase 3: PostgreSQL equivalents for the two SQLite behaviours the
-- existing repository SQL relies on. Keeping them here (instead of forking the
-- queries per dialect) means the authorization SQL is byte-for-byte the same in
-- local/demo (SQLite) and production/Azure (Neon PostgreSQL).

-- 1. Document ACLs: backend/src/authorization/policy.ts filters on
--    EXISTS (SELECT 1 FROM json_each(d.allowed_users_json) WHERE value = ?)
--    SQLite's json_each(text) yields one row per array element with a `value`
--    column. PostgreSQL's built-in json_each(json) only accepts objects, so we
--    add a text overload with SQLite's array semantics: exact element match,
--    NULL input -> no rows, malformed JSON -> error (never a silent grant).
CREATE OR REPLACE FUNCTION json_each(doc TEXT)
RETURNS TABLE (key INTEGER, value TEXT)
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
AS $$
	SELECT (t.ord - 1)::INTEGER, t.elem
	FROM json_array_elements_text(doc::json) WITH ORDINALITY AS t(elem, ord)
$$;

-- 2. Message ordering: conversations/service.ts orders a conversation's
--    messages by (created_at, rowid). SQLite's implicit rowid is insertion
--    order; this identity column gives PostgreSQL the same tie-breaker.
ALTER TABLE messages ADD COLUMN IF NOT EXISTS rowid BIGINT GENERATED BY DEFAULT AS IDENTITY;
CREATE INDEX IF NOT EXISTS idx_messages_conv_order ON messages (conversation_id, created_at, rowid);
